#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "microbin"
name = "MicroBin"
description.en = "Configurable file-sharing and URL shortening web app"
description.fr = "Partage de fichiers et de raccourcissement d'URL"

version = "2.0.4~ynh6"

maintainers = ["eric_G"]

[upstream]
license = "BSD-3-Clause"
website = "https://microbin.eu/"
demo = "https://pub.microbin.eu/"
code = "https://github.com/szabodanika/microbin"
fund = "https://ko-fi.com/dani_sz"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/szabodanika/microbin/releases/download/v2.1.0/microbin-v2.1.0-x86_64-unknown-linux-musl.tar.gz"
    amd64.sha256 = "3d6285b4520340c0611875916a7b1dbfa880973541f044c3d18efce799725f45"
    arm64.url = "https://github.com/szabodanika/microbin/releases/download/v2.1.0/microbin-v2.1.0-aarch64-unknown-linux-musl.tar.gz"
    arm64.sha256 = "sha256:d85f2259404587b1b7b6e585d9fc63e53b0253294cd0a96593ecb0355228f88a"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    
    list.url = "/list"
    list.show_tile = false
    list.allowed = "all_users"
    
    upload.url = "/upload"
    upload.show_tile = false   
    upload.allowed = ["all_users", "visitors"]
    
 #   static.url = "/static"
 #   static.show_tile = false   
 #   static.allowed = "visitors"
    
 #   raw.url = "/raw/"
 #   raw.show_tile = false   
 #   raw.allowed = ["all_users", "visitors"]
    
    qr.url = "/qr"
    qr.show_tile = false   
    qr.allowed = ["all_users", "visitors"]
    
    p.url = "/p"
    p.show_tile = false   
    p.allowed = ["all_users", "visitors"]

    [resources.ports]
